version: '2'
services:
  mongo:
    image: mongo:3
    volumes:
      - db:/data/db

  backup:
    build: .
    volumes:
      - /tmp/backup:/backup
    depends_on:
      - mongo
    environment:
      MONGO_HOST: 'mongo'
      MONGO_PORT: 27017
      CRON_TIME: '* * * * *'
      INIT_BACKUP: 1

volumes:
  db:
    driver: local
